---
- name: validate buffersize variable
  assert:
    that:
      - openwrt_system_buffersize | type_debug == 'int'
    fail_msg: "openwrt_system_buffersize must be of type integer."
    success_msg: "openwrt_system_buffersize seems valid."
  when: openwrt_system_buffersize is defined
- name: validate conloglevel variable
  assert:
    that:
      - openwrt_system_conloglevel | type_debug == 'int'
      - openwrt_system_conloglevel >= 0
      - openwrt_system_conloglevel < 10
    fail_msg: "openwrt_system_conloglevel must be of type integer and between 1 and 8."
    success_msg: "openwrt_system_conloglevel is valid."
  when: openwrt_system_conloglevel is defined
- name: validate cronloglevel variable
  assert:
    that:
      - openwrt_system_cronloglevel | type_debug == 'int'
      - openwrt_system_cronloglevel is regex("^[0-20]+$")
    fail_msg: "openwrt_system_conloglevel must be of type integer of 1 or bigger."
    success_msg: "openwrt_system_conloglevel is valid."
  when: openwrt_system_cronloglevel is defined
- name: validate openwrt_system_log_proto variable
  assert:
    that:
      - (openwrt_system_log_proto | lower == 'tcp') or (openwrt_system_log_proto | lower == 'udp')
    fail_msg: "openwrt_system_log_proto must be either tcp or udp."
    success_msg: "openwrt_system_log_proto seems valid."
  when: openwrt_system_log_proto is defined
- name: validate_system_ntpservers variable
  assert:
    that:
      - openwrt_system_ntpservers | type_debug == 'list'
    fail_msg: "openwrt_system_ntpservers must be of type list."
    success_msg: "openwrt_system_ntpservers is a list."
  when: openwrt_system_ntpservers is defined
