---
# defaults file for ansible_openwrtfirewall
openwrt_firewall_default_forward: "REJECT"
openwrt_firewall_default_input: "ACCEPT"
openwrt_firewall_default_output: "ACCEPT"
openwrt_firewall_default_synflood: 1
openwrt_firewall_default_flowoffloading: 1
openwrt_firewall_default_flowoffloadinghw: 1
openwrt_firewall_default_rules:
  - name: "Allow-Ping"
    family: "ipv4"
    icmp_types:
      - "echo-request"
    protos:
      - "icmp"
    src: "wan"
    target: "ACCEPT"
  - name: "Allow-IGMP"
    family: "ipv4"
    protos:
      - "igmp"
    src: "wan"
    target: "ACCEPT"
  - name: "Allow-DHCPv6"
    dest_ips:
      - "fc00::/6"
    dest_port: 546
    family: "ipv6"
    protos:
      - "udp"
    src: "wan"
    src_ips:
      - "fc00::/6"
    target: "ACCEPT"
  - name: "Allow-MLD"
    family: "ipv6"
    icmp_types:
      - "130/0"
      - "131/0"
      - "132/0"
      - "143/0"
    protos:
      - "icmp"
    src: "wan"
    src_ips:
      - "fe80::/10"
    target: "ACCEPT"
  - name: "Allow-ICMPv6-Input"
    family: "ipv6"
    icmp_types:
        -  "echo-request"
        -  "echo-reply"
        -  "destination-unreachable"
        -  "packet-too-big"
        -  "time-exceeded"
        -  "bad-header"
        -  "unknown-header-type"
        -  "router-solicitation"
        -  "neighbour-solicitation"
        -  "router-advertisement"
        -  "neighbour-advertisement"
    limit: "1000/sec"
    protos:
      - "icmp"
    src: "*"
    target: "ACCEPT"
  - name: "Allow-ICMPv6-Forward"
    family: "ipv6"
    icmp_types:
        -  "echo-request"
        -  "echo-reply"
        -  "destination-unreachable"
        -  "packet-too-big"
        -  "time-exceeded"
        -  "bad-header"
        -  "unknown-header-type"
        -  "router-solicitation"
        -  "neighbour-solicitation"
        -  "router-advertisement"
        -  "neighbour-advertisement"
    limit: "1000/sec"
    protos:
      - "icmp"
    src: "*"
    dest: "*"
    target: "ACCEPT"
  - name: "Allow-IPSec-ESP wan"
    dest: "lan"
    protos:
      - "esp"
    src: "wan"
    target: "ACCEPT"
  - name: "Allow-IPSec-ESP neighbours"
    dest: "lan"
    protos:
      - "esp"
    src: "neighbours"
    target: "ACCEPT"
  - name: "Allow-ISAKMP wan"
    dest: "lan"
    protos:
      - "udp"
    dest_port: 500
    src: "wan"
    target: "ACCEPT"
  - name: "Allow-ISAKMP neighbours"
    dest: "lan"
    protos:
      - "udp"
    dest_port: "500"
    src: "neighbours"
    target: "ACCEPT"
  - name: "Support-UDP-Traceroute wan"
    dest_port: "33434:33689"
    family: "ipv4"
    protos:
      - "udp"
    src: "wan"
    target: "REJECT"
    enabled: "0"
  - name: "Support-UDP-Traceroute neighbours"
    dest_port: "33434:33689"
    family: "ipv4"
    protos:
      - "udp"
    src: "neighbours"
    target: "REJECT"
    enabled: "0"
