---
# defaults file for ansible_openwrtfirewall
openwrt_firewall_default_forward: "REJECT"
openwrt_firewall_default_input: "ACCEPT"
openwrt_firewall_default_output: "ACCEPT"
openwrt_firewall_default_synflood_protect: "1"
openwrt_firewall_default_flow_offloading: "0"
openwrt_firewall_default_flow_offloading_hw: "0"
openwrt_firewall_default_wanzone: "wan"
openwrt_firewall_default_neighbourszone: "neighbours"
openwrt_firewall_default_guestszone: "guests"
openwrt_firewall_default_lanzone: "lan"
openwrt_firewall_default_dmzzone: "dmz"
openwrt_firewall_default_mgmtzone: "mgmt"
openwrt_firewall_default_zones:
  - name: "{{ openwrt_firewall_default_wanzone }}"
    forward: "REJECT"
    input: "REJECT"
    output: "ACCEPT"
    masq: "1"
    mtu_fix: "1"
  - name: "{{ openwrt_firewall_default_neighbourszone }}"
    forward: "ACCEPT"
    input: "REJECT"
    output: "REJECT"
  - name: "{{ openwrt_firewall_default_guestszone }}"
    forward: "ACCEPT"
    input: "REJECT"
    output: "ACCEPT"
  - name: "{{ openwrt_firewall_default_lanzone }}"
    forward: "ACCEPT"
    input: "ACCEPT"
    output: "ACCEPT"
  - name: "{{ openwrt_firewall_default_dmzzone }}"
    forward: "REJECT"
    input: "REJECT"
    output: "ACCEPT"
  - name: "{{ openwrt_firewall_default_mgmtzone }}"
    forward: "REJECT"
    input: "REJECT"
    output: "ACCEPT"
openwrt_firewall_default_rules:
  - name: "Allow-Ping wan to firewall"
    family: "ipv4"
    icmp_types:
      - "echo-request"
    protos:
      - "icmp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "ACCEPT"
  - name: "Allow-IGMP wan to firewall"
    family: "ipv4"
    protos:
      - "igmp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "ACCEPT"
  - name: "Allow-DHCPv6 wan"
    dest_ips:
      - "fc00::/6"
    dest_port: "546"
    family: "ipv6"
    protos:
      - "udp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    src_ips:
      - "fc00::/6"
    target: "ACCEPT"
  - name: "Allow-MLD wan"
    family: "ipv6"
    icmp_types:
      - "130/0"
      - "131/0"
      - "132/0"
      - "143/0"
    protos:
      - "icmp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    src_ips:
      - "fe80::/10"
    target: "ACCEPT"
  - name: "Allow-ICMPv6-Input"
    family: "ipv6"
    icmp_types:
        -  "echo-request"
        -  "echo-reply"
        -  "destination-unreachable"
        -  "packet-too-big"
        -  "time-exceeded"
        -  "bad-header"
        -  "unknown-header-type"
        -  "router-solicitation"
        -  "neighbour-solicitation"
        -  "router-advertisement"
        -  "neighbour-advertisement"
    limit: "1000/sec"
    protos:
      - "icmp"
    src: "*"
    target: "ACCEPT"
  - name: "Allow-ICMPv6-Forward any to any"
    family: "ipv6"
    icmp_types:
        -  "echo-request"
        -  "echo-reply"
        -  "destination-unreachable"
        -  "packet-too-big"
        -  "time-exceeded"
        -  "bad-header"
        -  "unknown-header-type"
        -  "router-solicitation"
        -  "neighbour-solicitation"
        -  "router-advertisement"
        -  "neighbour-advertisement"
    limit: "1000/sec"
    protos:
      - "icmp"
    src: "*"
    dest: "*"
    target: "ACCEPT"
  - name: "Allow-IPSec-ESP lan"
    dest: " {{ openwrt_firewall_default_lanzone }}"
    protos:
      - "esp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "ACCEPT"
  - name: "Allow-ISAKMP wan"
    dest: "{{ openwrt_firewall_default_lanzone }}"
    protos:
      - "udp"
    dest_port: "500"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "ACCEPT"
  - name: "Support-UDP-Traceroute wan"
    dest_port: "33434:33689"
    family: "ipv4"
    protos:
      - "udp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "REJECT"
    enabled: "0"
