---
# defaults file for ansible_openwrtfirewall
# global parameters
openwrt_firewall_default_forward: "REJECT"
openwrt_firewall_default_input: "ACCEPT"
openwrt_firewall_default_output: "ACCEPT"
openwrt_firewall_default_synflood_protect: "1"
openwrt_firewall_default_flow_offloading: "0"
openwrt_firewall_default_flow_offloading_hw: "0"
openwrt_firewall_default_drop_invalid: "0"
# default zone names, can be overwritten on group or host level
openwrt_firewall_default_wanzone: "wan"
openwrt_firewall_default_neighbourszone: "neighbours"
openwrt_firewall_default_guestszone: "guests"
openwrt_firewall_default_lanzone: "lan"
openwrt_firewall_default_dmzzone: "dmz"
openwrt_firewall_default_mgmtzone: "mgmt"
# default zones logging
openwrt_firewall_default_wanzone_logging: "1"
openwrt_firewall_default_neighbourszone_logging: "1"
openwrt_firewall_default_guestszone_logging: "1"
openwrt_firewall_default_lanzone_logging: "1"
openwrt_firewall_default_dmzzone_logging: "1"
openwrt_firewall_default_mgmtzone_logging: "1"
# default forwardings
openwrt_firewall_default_forwardings:
  - src: "{{ openwrt_firewall_default_lanzone }}"
    dest: "{{ openwrt_firewall_default_wanzone }}"
# default policies for the default zones
openwrt_firewall_default_zones:
  - name: "{{ openwrt_firewall_default_wanzone }}"
    forward: "REJECT"
    input: "REJECT"
    output: "ACCEPT"
    log: "{{ openwrt_firewall_default_wanzone_logging }}"
    masq: "1"
    mtu_fix: "1"
  - name: "{{ openwrt_firewall_default_neighbourszone }}"
    forward: "ACCEPT"
    input: "REJECT"
    output: "REJECT"
    log: "{{ openwrt_firewall_default_neighbourszone_logging }}"
  - name: "{{ openwrt_firewall_default_guestszone }}"
    forward: "ACCEPT"
    input: "REJECT"
    output: "ACCEPT"
    log: "{{ openwrt_firewall_default_guestszone_logging }}"
  - name: "{{ openwrt_firewall_default_lanzone }}"
    forward: "ACCEPT"
    input: "ACCEPT"
    output: "ACCEPT"
    log: "{{ openwrt_firewall_default_lanzone_logging }}"
  - name: "{{ openwrt_firewall_default_dmzzone }}"
    forward: "REJECT"
    input: "REJECT"
    output: "ACCEPT"
    log: "{{ openwrt_firewall_default_dmzzone_logging }}"
  - name: "{{ openwrt_firewall_default_mgmtzone }}"
    forward: "REJECT"
    input: "REJECT"
    output: "ACCEPT"
    log: "{{ openwrt_firewall_default_mgmtzone_logging }}"
# default rules
openwrt_firewall_default_rules:
  - name: "Allow-Ping wan to firewall"
    family: "ipv4"
    icmp_type:
      - "echo-request"
    proto:
      - "icmp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "ACCEPT"
  - name: "Allow-IGMP wan to firewall"
    family: "ipv4"
    proto:
      - "igmp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "ACCEPT"
  - name: "DHCPv4 neighbours"
    dest_port: "67"
    family: "ipv4"
    proto:
      - "udp"
    src: "{{ openwrt_firewall_default_neighbourszone }}"
    target: "ACCEPT"
  - name: "DHCPv4 guests"
    dest_port: "67"
    family: "ipv4"
    proto:
      - "udp"
    src: "{{ openwrt_firewall_default_guestszone }}"
    target: "ACCEPT"
  - name: "DHCPv4 lan"
    dest_port: "67"
    family: "ipv4"
    proto:
      - "udp"
    src: "{{ openwrt_firewall_default_lanzone }}"
    target: "ACCEPT"
  - name: "DHCPv4 mgmt"
    dest_port: "67"
    family: "ipv4"
    proto:
      - "udp"
    src: "{{ openwrt_firewall_default_mgmtzone }}"
    target: "ACCEPT"
  - name: "DHCPv4 dmz"
    dest_port: "67"
    family: "ipv4"
    proto:
      - "udp"
    src: "{{ openwrt_firewall_default_dmzzone }}"
    target: "ACCEPT"
  - name: "DHCPv6 mgmt"
    dest_port: "547"
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "{{ openwrt_firewall_default_mgmtzone }}"
    target: "ACCEPT"
  - name: "DHCPv6 guests"
    dest_port: "547"
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "{{ openwrt_firewall_default_guestszone }}"
    target: "ACCEPT"
  - name: "DHCPv6 lan"
    dest_port: "547"
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "{{ openwrt_firewall_default_lanzone }}"
    target: "ACCEPT"
  - name: "DHCPv6 dmz"
    dest_port: "547"
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "{{ openwrt_firewall_default_dmzzone }}"
    target: "ACCEPT"
  - name: "DHCPv6 mgmt"
    dest_port: "547"
    family: "ipv6"
    proto:
      - "udp"
    src_ip:
      - "fe80::/10"
    src: "{{ openwrt_firewall_default_mgmtzone }}"
    target: "ACCEPT"
  - name: "Allow-DHCPv6 wan"
    dest_ip:
      - "fc00::/6"
    dest_port: "546"
    family: "ipv6"
    proto:
      - "udp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    src_ip:
      - "fc00::/6"
    target: "ACCEPT"
  - name: "Allow-MLD wan"
    family: "ipv6"
    icmp_type:
      - "130/0"
      - "131/0"
      - "132/0"
      - "143/0"
    proto:
      - "icmp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    src_ip:
      - "fe80::/10"
    target: "ACCEPT"
  - name: "Allow-ICMPv6-Input"
    family: "ipv6"
    icmp_type:
        -  "echo-request"
        -  "echo-reply"
        -  "destination-unreachable"
        -  "packet-too-big"
        -  "time-exceeded"
        -  "bad-header"
        -  "unknown-header-type"
        -  "router-solicitation"
        -  "neighbour-solicitation"
        -  "router-advertisement"
        -  "neighbour-advertisement"
    limit: "1000/sec"
    proto:
      - "icmp"
    src: "*"
    target: "ACCEPT"
  - name: "Allow-ICMPv6-Forward any to any"
    family: "ipv6"
    icmp_type:
        - "destination-unreachable"
        - "packet-too-big"
        - "time-exceeded"
        - "parameter-problem"
        - "echo-request"
        - "echo-reply"
    limit: "1000/sec"
    proto:
      - "icmp"
    src: "*"
    dest: "*"
    target: "ACCEPT"
  - name: "Allow-IPSec-ESP lan"
    dest: " {{ openwrt_firewall_default_lanzone }}"
    proto:
      - "esp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "ACCEPT"
  - name: "Allow-ISAKMP wan"
    dest: "{{ openwrt_firewall_default_lanzone }}"
    proto:
      - "udp"
    dest_port: "500"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "ACCEPT"
  - name: "Support-UDP-Traceroute wan"
    dest_port: "33434:33689"
    family: "ipv4"
    proto:
      - "udp"
    src: "{{ openwrt_firewall_default_wanzone }}"
    target: "REJECT"
    enabled: "0"
