---
# tasks file for ansible_openwrtdhcp
- name: merge dhcp group pools
  include_tasks: merge.yml
  when: openwrt_dhcp_poolsgroup is defined
- name: Install dhcp config
  template:
    src: dhcp.jinja2
    dest: /etc/config/dhcp
    owner: root
    group: root
    mode: 0600
  notify: restart dnsmasq

