---
# defaults file for ansible_openwrtnetwork
openwrt_network_deploypath: "/etc/config/network"
openwrt_network_wg_keypath: "/etc/wireguard/ansiblekeys"
openwrt_network_interfacesdefault:
  loopback:
    device: "lo"
    proto: "static"
    ipaddr:
      - "127.0.0.1/8"
