---
# defaults file for ansible_openwrtrestic
openwrt_restic_cron_name: "resticbackup"
openwrt_restic_cron_hourrange_start: 1
openwrt_restic_cron_hourrange_end: 6
openwrt_restic_cron_minuterange_start: 1
openwrt_restic_cron_minuterange_end: 59
openwrt_restic_cron_hour: "{{ openwrt_restic_cron_hourrange_end | random(start=openwrt_restic_cron_hourrange_start, seed=inventory_hostname) }}"
openwrt_restic_cron_minute: "{{ openwrt_restic_cron_minuterange_end | random(start=openwrt_restic_cron_minuterange_start, seed=inventory_hostname) }}"
openwrt_restic_cron_manage: true
openwrt_restic_ssh_manage: true
openwrt_restic_keepweekly: 3
openwrt_restic_keepdaily: 9
openwrt_restic_keepmonthly: 2
openwrt_restic_deploypath: "/etc/restic"
openwrt_restic_deploypath_sysupgrade: "/etc/sysupgrade.conf"
openwrt_restic_deploypath_passwordfile: "/etc/resticpassword"
openwrt_restic_deploypath_knownhosts: "/root/.ssh/known_hosts"
