---
# tasks file for ansible_openwrtnetwork
- name: Deploy Network configuration 
  template:
    src: network.jinja2
    dest: "{{ openwrt_network_deploypath }}"
    owner: root
    group: root
    mode: 0600
  notify: restart network
