# Merge Interfaces
- name: merge group interfaces
  set_fact:
    openwrt_network_interfacesmergedgroup: "{{ openwrt_network_interfacesgroup.keys() | list | intersect(group_names) | map('extract', openwrt_network_interfacesgroup) | combine }}"
  when: openwrt_network_interfacesgroup is defined
- name: combine all interfaces into openwrt_network_interfaces
  set_fact:
    openwrt_network_interfaces: "{{ openwrt_network_interfaceshost | default({}) | combine(openwrt_network_interfacesmergedgroup | default({}) ) }}"
# Merge Devices
- name: merge group devices
  set_fact:
    openwrt_network_devicesmergedgroup: "{{ openwrt_network_devicesgroup.keys() | list | intersect(group_names) | map('extract', openwrt_network_devicesgroup) | combine }}"
  when: openwrt_network_devicesgroup is defined
- name: combine all devices into openwrt_network_devices
  set_fact:
    openwrt_network_devices: "{{ openwrt_network_deviceshost | default({}) | combine(openwrt_network_devicesmergedgroup | default({}) ) }}"
