---
# tasks file for ansible_openwrtbabeld
- name: Refresh opkg so packages will be found
  shell: opkg update
  when:
    not openwrt_babeld_runimagebuilder | default(false)
- name: Install jq in order to be able to parse ifstatus
  package:
    name: jq
    state: present
  when:
    not openwrt_babeld_runimagebuilder | default(false)
- name: Install getprefix script
  template:
    src: getprefix.sh.jinja2
    dest: /root/getprefix.sh
    owner: root
    group: root
    mode: 0744
  when:
    not openwrt_babeld_runimagebuilder | default(false)
- name: register dynamic prefixes from script
  shell: /root/getprefix.sh
  register: openwrt_babeld_collectedprefixes
  when:
    not openwrt_babeld_runimagebuilder | default(false)
# here shall be a task that sets the prefixes to distribute manually
# by giving specific, predefined prefixes for redistribution
#- name: register dynamic prefix from variable
#  set_fact: openwrt_babeld_collectedprefixes
#  when:
#    openwrt_babeld_runimagebuilder | default(false)
- name: register local ula
  shell: /sbin/uci get network.globals.ula_prefix
  register: openwrt_babeld_ulaprefix
  when:
    not openwrt_babeld_runimagebuilder | default(false)
- name: Provide babeld configuration
  template:
    src: babeld.jinja2
    dest: "{{ openwrt_babeld_deploypath }}"
    owner: root
    group: root
    mode: 0600
  notify: restart babeld
- name: enable babeld service
  service:
    name: babeld
    state: started
    enabled: yes
  when:
    not openwrt_babeld_runimagebuilder | default(false)
- name: enable babeld service in imagebuilder
  ansible.builtin.file:
    src: ../init.d/babeld
    dest: "{{ openwrt_babeld_deploypath_initlink }}"
    state: link
  when:
    openwrt_babeld_runimagebuilder | default(false)
