---
# tasks file for ansible_openwrtservices
- name: Enable Serices
  command: /etc/init.d/{{ item }} enable
  loop: "{{ openwrt_services_enabled }}"
  when: openwrt_services_enabled is defined
- name: Start Services
  command: /etc/init.d/{{ item }} start
  loop: "{{ openwrt_services_enabled }}"
  when: openwrt_services_enabled is defined
- name: Disable Services
  command: /etc/init.d/{{ item }} disable
  loop: "{{ openwrt_services_disabled }}"
  when: openwrt_services_disabled is defined
- name: Stop Services
  command: /etc/init.d/{{ item }} stop
  loop: "{{ openwrt_services_disabled }}"
  when: openwrt_services_disabled is defined
- name: Setup Start Scripts in /etc/rc.local
  template:
    src: rc.local.jinja2
    dest: "{{ openwrt_services_deploypath }}"
    owner: root
    group: root
    mode: 0600
  when: openwrt_scriptlinesafterboot is defined
