---
# waiting for Ansible 2.11 and this feature
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-argument-validation
# Global Firewall parameters
#- name: Check firewall global policies
#  include_tasks: checks/accept_reject_drop.yml
#  loop:
#    - "{{ openwrt_firewall_default_forward }}"
#    - "{{ openwrt_firewall_default_input }}"
#    - "{{ openwrt_firewall_default_output }}"
#  loop_control:
#    loop_var: policyitemA
#      #no_log: true
#- name: Check firewall global booleans
#  include_tasks: checks/boolean.yml
#  loop:
#    - "{{ openwrt_firewall_default_drop_invalid | default(omit) }}"
#    - "{{ openwrt_firewall_default_synflood | default(omit) }}"
#    - "{{ openwrt_firewall_default_synflood_protect | default(omit) }}"
#    - "{{ openwrt_firewall_default_tcp_syncookies | default(omit) }}"
#    - "{{ openwrt_firewall_default_tcp_ecn | default(omit) }}"
#    - "{{ openwrt_firewall_default_tcp_window_scaling | default(omit) }}"
#    - "{{ openwrt_firewall_default_accept_redirects | default(omit) }}"
#    - "{{ openwrt_firewall_default_accept_source_route | default(omit) }}"
#    - "{{ openwrt_firewall_default_custom_chains | default(omit) }}"
#    - "{{ openwrt_firewall_default_disable_ipv6 | default(omit) }}"
#    - "{{ openwrt_firewall_default_flow_offloading | default(omit) }}"
#    - "{{ openwrt_firewall_default_flow_offloading_hw | default(omit) }}"
#    - "{{ openwrt_firewall_default_auto_helper | default(omit) }}"
#  loop_control:
#    loop_var: booleanitem
#  no_log: true
#- name: run zone checks
#  include_tasks: checks/zones.yml
#  loop:
#    - "{{ openwrt_firewall_zoneshost | default(omit) }}"
#    - "{{ openwrt_firewall_zonesdefault | default(omit) }}"
#  loop_control:
#    loop_var: zones
      # check somehow not working
      #- name: Check all variables that either need to be 1 or 0
      #  assert:
      #    that:
      #      - item is int
      #        #- item == 1 or item == 0
      #    fail_msg: "{{ item }} needs to be 1 or 0."
      #    success_msg: "{{ item }} is valid."
      #  loop:
      #    - "openwrt_firewall_default_synflood_protect"
      #    - "openwrt_firewall_default_flow_offloading"
      #    - "openwrt_firewall_default_flow_offloading_hw"
      #    - "openwrt_firewall_default_drop_invalid"
- name: check default forwards
  assert:
    that:
      - item.src is defined
      - item.dest is defined
    fail_msg: "forwarding list item needs a src AND dest key."
    success_msg: "forwarding item seems valid."
  loop: "{{ openwrt_firewall_forwardingsdefault }}"
  when: openwrt_firewall_forwardingsdefault is defined
- name: check host based forwardings
  assert:
    that:
      - item.src is defined
      - item.dest is defined
    fail_msg: "forwarding list item needs a src AND dest key."
    success_msg: "host forwardings seem valid."
  loop: "{{ openwrt_firewall_forwardingshost }}"
  when: openwrt_firewall_forwardingshost is defined
- name: check group based forwardings
  assert:
    that:
      - item.src is defined
      - item.dest is defined
    fail_msg: "forwarding list item needs a src AND dest key."
    success_msg: "host forwardings seem valid."
  loop: "{{ openwrt_firewall_forwardingsmergedgroup }}"
  when: openwrt_firewall_forwardingsmergedgroup is defined
    # this check is bullshit, need to write new checks for rules
    #- name: rudimentary checks on rules
    #  assert:
    #    that:
    #      - item.value.src is defined
    #    fail_msg: "Rule {{ item.key}} contains errors, it has no attribute src."
    #    success_msg: "Rule {{ item.key }} seems OK."
    #  loop: "{{ openwrt_firewall_rulesall | dict2items }}"
    #- name: show all rules
    #  debug:
    #    var: openwrt_firewall_rulesall
    #- name: show all zones
    #  debug:
    #    var: openwrt_firewall_zonesall
