---
# tasks file for ansible_openwrtfirewall
- name: declare emtpy zone array
  set_fact:
    openwrt_firewall_zonesactive: []
- name: Run checks on variables
  import_tasks: checks.yml
- name: Merge rules, zones and forwardings
  import_tasks: merge.yml
- name: Make a list of all active zones
  set_fact:
    openwrt_firewall_zonesactive: "{{ openwrt_firewall_zonesactive + [ item.key ] }}"
  when:
    - ( item.value.disabled is not defined ) or ( item.value.disabled is defined and not item.value.disabled )
  loop: "{{ openwrt_firewall_zonesall | dict2items }}"
- name: Create firewall uci in /etc/config/firewall
  template:
    src: "firewall.jinja2"
    dest: "{{ openwrt_firewall_deploypath }}"
    owner: root
    group: root
    mode: 0600
  notify: reload firewall
